const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const listings=[
 {id:1,title:'Piso en calle de Alcalá, Goya',price:2450,rooms:3,size:112,img:'assets/property-hero.svg',desc:'Vivienda luminosa, reformada y con terraza en una de las mejores zonas de Madrid.'},
 {id:2,title:'Ático en Malasaña-Universidad',price:1850,rooms:2,size:78,img:'assets/rooms-hero.svg',desc:'Ático exterior con gran salón, cocina equipada y vistas abiertas.'},
 {id:3,title:'Piso en barrio de Salamanca',price:3200,rooms:4,size:145,img:'assets/virtual-visit.svg',desc:'Piso señorial, portero físico y plaza de garaje incluida.'}
];
const saved=[{id:'madrid',title:'Pisos en Madrid',meta:'Alquiler · hasta 2.500 €/mes',img:'assets/property-hero.svg'},{id:'centro',title:'Centro y Chamberí',meta:'Compra · 2 o más habitaciones',img:'assets/rooms-hero.svg'}];
const chats=[{id:1,name:'Lucía · Particular',preview:'Sí, podemos organizar una visita mañana.',time:'12:42',unread:2},{id:2,name:'Inmobiliaria Centro',preview:'Te enviamos la documentación del piso.',time:'Ayer',unread:0}];
const state={route:location.hash.slice(1)||'home',operation:'Alquilar',location:'Madrid',map:false,sort:'relevance',filter:{min:'',max:'',rooms:0},favorites:new Set(JSON.parse(localStorage.getItem('favorites')||'[]')),dark:localStorage.getItem('dark')==='1',alerts:JSON.parse(localStorage.getItem('alerts')||'{"madrid":true,"centro":false}'),messages:{1:[{me:false,text:'Hola, ¿sigues interesado en el piso?',time:'12:31'},{me:true,text:'Sí. ¿Podemos visitarlo mañana?',time:'12:35'},{me:false,text:'Sí, podemos organizar una visita mañana.',time:'12:42'}],2:[{me:false,text:'Te enviamos la documentación del piso.',time:'Ayer'}]}};
const screen=$('#screen'),nav=$('#bottom-nav'),sheet=$('#sheet-root'),toastRoot=$('#toast-root');
const save=()=>{localStorage.setItem('favorites',JSON.stringify([...state.favorites]));localStorage.setItem('dark',state.dark?'1':'0');localStorage.setItem('alerts',JSON.stringify(state.alerts))};
const icon=n=>({home:'⌂',alerts:'♧',favorites:'♡',chat:'▣',menu:'☰',search:'⌕',filter:'≡',map:'⌖',list:'☷',back:'←',share:'↗',phone:'☎',mail:'✉',heart:'♡',heartOn:'♥',camera:'▣',user:'○',bell:'♧'}[n]||'•');
function route(r){state.route=r;location.hash=r;render()}
function toolbar(title,{brand=false,back=false,right=''}={}){return `<header class="toolbar ${brand?'brand':''}">${back?`<button class="toolbar-action left" data-act="back">${icon('back')}</button>`:''}<strong class="toolbar-title">${title}</strong>${right?`<button class="toolbar-action right" data-act="${right}">${icon(right)}</button>`:''}</header>`}
function navHtml(){const base=state.route.split('/')[0],items=[['home','home','Buscar'],['alerts','alerts','Alertas'],['favorites','favorites','Favoritos'],['chat','chat','Chat'],['menu','menu','Menú']];return items.map(([r,i,l])=>`<button class="nav-item ${base===r?'active':''}" data-route="${r}"><span class="icon">${icon(i)}</span><span>${l}</span></button>`).join('')}
function home(){return `${toolbar('idealista',{brand:true})}<div class="page"><div class="home-grid"><section class="hero"><img src="assets/property-hero.svg"><div class="hero-info"><div class="hero-kicker">La casa del día</div><div class="hero-title">Piso con terraza en Madrid</div><div class="hero-price">2.450 €/mes</div></div></section><form class="search-panel" id="searchForm"><div class="segments">${['Comprar','Alquilar','Compartir'].map(x=>`<button type="button" class="segment ${state.operation===x?'active':''}" data-operation="${x}">${x}</button>`).join('')}</div><label class="field"><span>${icon('search')}</span><select id="typology"><option>Viviendas</option><option>Habitaciones</option><option>Garajes</option><option>Locales</option></select></label><label class="field"><span>${icon('map')}</span><input id="location" value="${state.location}" placeholder="¿Dónde buscas?"></label><button class="btn primary block">Buscar</button></form></div><section class="home-actions"><button class="btn secondary block" data-act="publish">Publicar anuncio gratis</button></section><section class="saved-searches"><h2 class="section-title">Tus búsquedas</h2>${saved.map(s=>`<article class="saved-card" data-route="results"><img class="saved-thumb" src="${s.img}"><div><div class="saved-title">${s.title}</div><div class="saved-meta">${s.meta}</div></div><span class="chev">›</span></article>`).join('')}</section></div>`}
function filtered(){let a=[...listings];const min=+state.filter.min||0,max=+state.filter.max||Infinity;if(state.filter.rooms)a=a.filter(x=>x.rooms>=state.filter.rooms);a=a.filter(x=>x.price>=min&&x.price<=max);if(state.sort==='priceAsc')a.sort((a,b)=>a.price-b.price);if(state.sort==='priceDesc')a.sort((a,b)=>b.price-a.price);return a}
function card(x){const on=state.favorites.has(x.id);return `<article class="listing-card"><img class="listing-image" src="${x.img}" data-detail="${x.id}"><button class="fav-btn ${on?'on':''}" data-fav="${x.id}">${icon(on?'heartOn':'heart')}</button><span class="photo-count">${icon('camera')} 12</span><div class="listing-content" data-detail="${x.id}"><h3 class="listing-title">${x.title}</h3><div class="listing-price">${x.price.toLocaleString('es-ES')} €/mes</div><div class="listing-features">${x.rooms} hab. · ${x.size} m²</div><p class="listing-description">${x.desc}</p></div></article>`}
function results(){const a=filtered();return `${toolbar(state.location,{back:true})}<div class="page"><div class="result-tools"><div class="result-summary"><div><div class="result-count">${a.length} viviendas</div><div class="subtle body-s">${state.operation} en ${state.location}</div></div><button class="btn tertiary" data-act="modify">Modificar</button></div><div class="tool-row"><button class="tool" data-act="filter">${icon('filter')} Filtrar</button><button class="tool" data-act="sort">Ordenar</button><button class="tool ${state.map?'active':''}" data-act="map">${icon(state.map?'list':'map')} ${state.map?'Lista':'Mapa'}</button></div></div>${state.map?mapView(a):`<div class="listings">${a.map(card).join('')||'<div class="empty"><h2>Sin resultados</h2><p>Prueba otros filtros.</p></div>'}</div>`}</div>`}
function mapView(a){const x=a[0]||listings[0];return `<section class="map-view"><div class="map-grid"></div><div class="map-water"></div>${a.map((p,i)=>`<button class="pin ${i===0?'selected':''}" style="left:${25+i*24}%;top:${28+i*16}%" data-detail="${p.id}">${p.price.toLocaleString('es-ES')} €</button>`).join('')}<article class="map-card" data-detail="${x.id}"><img src="${x.img}"><div class="map-card-body"><div class="map-card-title">${x.title}</div><div class="map-card-price">${x.price.toLocaleString('es-ES')} €/mes</div><div>${x.rooms} hab. · ${x.size} m²</div></div></article></section>`}
function detail(id){const x=listings.find(v=>v.id==id)||listings[0],on=state.favorites.has(x.id);return `<div class="page"><section class="detail-gallery"><img src="${x.img}"><div class="gallery-top"><button class="round" data-act="back">${icon('back')}</button><div class="rounds"><button class="round" data-act="share">${icon('share')}</button><button class="round ${on?'on':''}" data-fav="${x.id}">${icon(on?'heartOn':'heart')}</button></div></div><span class="gallery-indicator">1 / 12</span></section><main class="detail-main"><h1>${x.title}</h1><div class="detail-location">Madrid</div><div class="detail-price">${x.price.toLocaleString('es-ES')} €/mes</div><div class="detail-features">${x.rooms} habitaciones · ${x.size} m² · planta 3ª exterior</div><div class="chips"><span class="chip">Terraza</span><span class="chip">Ascensor</span><span class="chip">Aire acondicionado</span></div><section class="detail-block"><h2>Comentario del anunciante</h2><p>${x.desc} La vivienda se entrega amueblada y está disponible para entrar a vivir. Gastos de comunidad incluidos.</p></section><section class="detail-block"><h2>Características básicas</h2><p>Buen estado · Armarios empotrados · Orientación sur · Construido en 1998</p></section></main><div class="contact-bar"><button class="btn secondary" data-act="call">${icon('phone')} Llamar</button><button class="btn primary" data-act="message">${icon('mail')} Mensaje</button></div></div>`}
function alerts(){return `${toolbar('Alertas',{brand:true})}<div class="page">${saved.map(s=>`<article class="alert-card"><img src="${s.img}"><div><div class="alert-title">${s.title}</div><div class="alert-meta">${s.meta}</div></div><button class="switch ${state.alerts[s.id]?'on':''}" data-alert="${s.id}"></button></article>`).join('')}<div class="pad"><button class="btn primary block" data-route="home">Crear nueva alerta</button></div></div>`}
function favorites(){const a=listings.filter(x=>state.favorites.has(x.id));return `${toolbar('Favoritos',{brand:true})}<div class="page">${a.length?`<div class="listings">${a.map(card).join('')}</div>`:`<section class="empty"><img src="assets/img_empty_state_favorite.svg"><h2>Aún no tienes favoritos</h2><p>Guarda los anuncios que te gusten para encontrarlos aquí.</p><button class="btn primary" data-route="home">Buscar viviendas</button></section>`}</div>`}
function chat(){return `${toolbar('Chat',{brand:true})}<div class="page">${chats.map(c=>`<article class="conversation" data-thread="${c.id}"><div class="avatar">${c.name[0]}</div><div><div class="conv-name">${c.name}</div><div class="conv-preview">${c.preview}</div></div><div><div class="conv-time">${c.time}</div>${c.unread?`<div class="unread">${c.unread}</div>`:''}</div></article>`).join('')}</div>`}
function thread(id){const c=chats.find(x=>x.id==id)||chats[0],m=state.messages[c.id]||[];return `${toolbar(c.name,{back:true,right:'phone'})}<div class="thread"><div class="messages" id="messages">${m.map(x=>`<div class="bubble ${x.me?'me':''}">${escapeHtml(x.text)}<span class="bubble-time">${x.time}</span></div>`).join('')}</div><form class="composer" id="composer"><input id="messageInput" placeholder="Escribe un mensaje"><button class="send">${icon('mail')}</button></form></div>`}
function group(title,rows){return `<section class="menu-group"><div class="menu-heading">${title}</div>${rows.map(r=>`<button class="menu-row" data-menu="${r[2]}"><span>${icon(r[0])}</span><span><span class="menu-row-title">${r[1]}</span></span><span class="chev">›</span></button>`).join('')}</section>`}
function menu(){return `${toolbar('Menú',{brand:true})}<div class="page"><section class="user-card"><div class="avatar">BG</div><div><div class="user-name">Bogdan</div><div class="user-email">Cuenta de demostración</div></div></section>${group('Tu cuenta',[['user','Perfil','profile'],['heart','Listas de favoritos','favorites'],['home','Tus anuncios','publish']])}${group('Ajustes',[['bell','Notificaciones','alerts'],[state.dark?'home':'favorites','Apariencia','theme'],['menu','Privacidad','noop']])}<div class="pad"><button class="btn danger block" data-act="logout">Salir de tu cuenta</button></div></div>`}
function profile(){return `${toolbar('Perfil',{brand:true,back:true})}<div class="page"><section class="user-card"><div class="avatar">BG</div><div><div class="user-name">Bogdan</div><div class="user-email">bogdan@example.com</div></div></section>${group('Datos personales',[['user','Nombre y apellidos','noop'],['mail','Correo electrónico','noop'],['phone','Teléfono','noop']])}${group('Seguridad',[['menu','Cambiar contraseña','noop'],['menu','Verificación en dos pasos','noop']])}</div>`}
function showSheet(title,body){sheet.innerHTML=`<div class="sheet-backdrop"><section class="sheet"><div class="sheet-handle"></div><div class="sheet-head"><h2>${title}</h2><button class="sheet-close" data-act="close">×</button></div><div class="sheet-body">${body}</div></section></div>`}
function filters(){showSheet('Filtrar',`<div class="filter-label">Precio</div><div class="range-row"><input id="min" class="input" type="number" placeholder="Mínimo" value="${state.filter.min}"><input id="max" class="input" type="number" placeholder="Máximo" value="${state.filter.max}"></div><div class="filter-label">Habitaciones</div><div class="check-row">${[0,1,2,3,4].map(n=>`<button class="check ${state.filter.rooms===n?'on':''}" data-room="${n}">${n?n+(n===4?'+':''):'Todas'}</button>`).join('')}</div><button class="btn primary block" style="margin-top:24px" data-act="apply">Ver resultados</button>`)}
function sort(){showSheet('Ordenar',`<div class="check-row" style="display:grid"><button class="check" data-sort="relevance">Relevancia</button><button class="check" data-sort="priceAsc">Precio más bajo</button><button class="check" data-sort="priceDesc">Precio más alto</button></div>`)}
function publish(){showSheet('Publica tu anuncio',`<form class="publish-form" id="publishForm"><label>Tipo<select class="input"><option>Vivienda</option><option>Habitación</option></select></label><label>Dirección<input class="input" required></label><label>Precio<input class="input" type="number" required></label><label>Descripción<textarea required></textarea></label><button class="btn primary block">Guardar borrador</button></form>`)}
function toast(t){toastRoot.innerHTML=`<div class="toast">${t}</div>`;setTimeout(()=>toastRoot.innerHTML='',1800)}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(){document.body.classList.toggle('dark',state.dark);const [b,id]=state.route.split('/'),show=['home','alerts','favorites','chat','menu'].includes(b);nav.classList.toggle('hidden',!show);nav.innerHTML=show?navHtml():'';screen.classList.toggle('no-nav',!show);screen.innerHTML=b==='home'?home():b==='results'?results():b==='detail'?detail(id):b==='alerts'?alerts():b==='favorites'?favorites():b==='chat'?chat():b==='thread'?thread(id):b==='menu'?menu():b==='profile'?profile():home();$('#searchForm')?.addEventListener('submit',e=>{e.preventDefault();state.location=$('#location').value||'Madrid';route('results')});$('#composer')?.addEventListener('submit',e=>{e.preventDefault();const i=$('#messageInput'),t=i.value.trim();if(!t)return;const cid=+state.route.split('/')[1];state.messages[cid].push({me:true,text:t,time:new Date().toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'})});render();setTimeout(()=>{$('#messages').scrollTop=99999},0)});$('#publishForm')?.addEventListener('submit',e=>{e.preventDefault();sheet.innerHTML='';toast('Borrador guardado')})}
document.addEventListener('click',e=>{const r=e.target.closest('[data-route]');if(r){route(r.dataset.route);return}const op=e.target.closest('[data-operation]');if(op){state.operation=op.dataset.operation;render();return}const d=e.target.closest('[data-detail]');if(d){route('detail/'+d.dataset.detail);return}const f=e.target.closest('[data-fav]');if(f){e.stopPropagation();const id=+f.dataset.fav;state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);save();render();return}const a=e.target.closest('[data-alert]');if(a){state.alerts[a.dataset.alert]=!state.alerts[a.dataset.alert];save();render();return}const t=e.target.closest('[data-thread]');if(t){route('thread/'+t.dataset.thread);return}const m=e.target.closest('[data-menu]');if(m){const x=m.dataset.menu;if(x==='theme'){state.dark=!state.dark;save();render()}else if(x==='publish')publish();else if(x==='noop')toast('Раздел готовится');else route(x);return}const room=e.target.closest('[data-room]');if(room){state.filter.rooms=+room.dataset.room;filters();return}const so=e.target.closest('[data-sort]');if(so){state.sort=so.dataset.sort;sheet.innerHTML='';render();return}const act=e.target.closest('[data-act]');if(!act)return;const x=act.dataset.act;if(x==='back')history.length>1?history.back():route('home');if(x==='modify')route('home');if(x==='filter')filters();if(x==='sort')sort();if(x==='map'){state.map=!state.map;render()}if(x==='close')sheet.innerHTML='';if(x==='apply'){state.filter.min=$('#min').value;state.filter.max=$('#max').value;sheet.innerHTML='';render()}if(x==='publish')publish();if(x==='share'){navigator.clipboard?.writeText(location.href);toast('Enlace copiado')}if(x==='call')toast('Llamando…');if(x==='message')route('thread/1');if(x==='phone')toast('Llamando…');if(x==='logout')toast('Сеанс завершён')});
sheet.addEventListener('click',e=>{if(e.target.classList.contains('sheet-backdrop'))sheet.innerHTML=''});window.addEventListener('hashchange',()=>{state.route=location.hash.slice(1)||'home';render()});render();
