const $=(s,r=document)=>r.querySelector(s);
const screen=$('#screen'),nav=$('#bottomNav'),overlay=$('#overlay'),toastRoot=$('#toastRoot');
const logo=`<svg class="logo" viewBox="0 0 112 32" aria-label="idealista"><path fill="currentColor" d="M6.05 4H3.03v3h3.02V4Zm48.44 0v3h3.02v18h3.03V4h-6.05ZM9.08 13h3.03v9H9.08v-9Zm9.08-9v6h-6.05v3h6.05v9h-6.05v3h9.08V4h-3.03ZM39.35 19h3.03v3h-3.03v-3Zm9.08-6v3h-6.05v3h6.05v3h-6.05v3h9.08V13h-3.03Zm-6.05-3h6.05v3h-6.05v-3Zm60.54 9h-3.03v3h3.03v-3Zm6.05-3v-3H112v12h-9.08v-3h6.05v-3h-6.05v-3h6.05Zm0-6h-6.05v3h6.05v-3ZM33.3 16v-3h3.02v6H27.24v3h-3.02v-9h3.02v3h6.06Zm0-6h-6.06v3h6.06v-3Zm-6.06 12h6.06v3h-6.06v-3ZM0 10v3h3.03v12h3.02V10H0Zm66.59-6h3.03v3h-3.03V4Zm30.27 9v-3h-3.02V4h-3.03v6h-3.03v3h3.03v9h3.03v-9h3.02Zm-3.02 9h3.02v3h-3.02v-3ZM84.76 10h-9.08v3h9.08v-3Zm-9.08 6h6.05v3h-6.05v-3Zm0-3v3h-3.03v-3h3.03Zm6.05 9h-9.08v3h9.08v-3Zm3.03-3h-3.03v3h3.03v-3ZM63.57 13v-3h6.05v15h-3.03V13h-3.02Z"/></svg>`;
const icons={home:'⌂',alerts:'♧',fav:'♡',chat:'▣',menu:'☰',back:'←',map:'⌖',filter:'≡',sort:'⇅',heart:'♡',heartOn:'♥',phone:'☎',mail:'✉'};
const listings=[
{id:1,title:'Piso en calle de Alcalá, Goya',price:'2.450 €/mes',meta:'3 hab. · 112 m² · planta 3ª exterior',img:'assets/property-hero.svg',desc:'Vivienda luminosa, reformada y con terraza en una de las mejores zonas de Madrid.'},
{id:2,title:'Ático en Malasaña-Universidad',price:'1.850 €/mes',meta:'2 hab. · 78 m² · planta 5ª exterior',img:'assets/rooms-hero.svg',desc:'Ático exterior con gran salón, cocina equipada y vistas abiertas.'},
{id:3,title:'Piso en barrio de Salamanca',price:'3.200 €/mes',meta:'4 hab. · 145 m² · planta 2ª exterior',img:'assets/virtual-visit.svg',desc:'Piso señorial con portero físico y plaza de garaje incluida.'}
];
const state={route:location.hash.slice(1)||'home',operation:'Alquilar',location:'Madrid',map:false,favs:new Set(JSON.parse(localStorage.getItem('idealFavs')||'[]'))};
const save=()=>localStorage.setItem('idealFavs',JSON.stringify([...state.favs]));
function go(r){state.route=r;location.hash=r;render();window.scrollTo(0,0)}
function toolbar(title,{brand=false,back=false}={}){return `<header class="toolbar ${brand?'brand':''}">${back?`<button class="toolbar-action left" data-go="home">${icons.back}</button>`:''}${brand?logo:`<div class="toolbar-title">${title}</div>`}</header>`}
function navHtml(){const base=state.route.split('/')[0];return [['home','home','Buscar'],['alerts','alerts','Alertas'],['favorites','fav','Favoritos'],['chat','chat','Chat'],['menu','menu','Menú']].map(([r,i,l])=>`<button class="nav-item ${base===r?'active':''}" data-go="${r}"><span style="font-size:24px;line-height:1">${icons[i]}</span><span>${l}</span></button>`).join('')}
function home(){return `${toolbar('',{brand:true})}<div class="page"><section class="hero"><img src="assets/property-hero.svg" alt="Vivienda"><div class="hero-info"><div class="hero-info-title">Encuentra tu casa</div><div class="hero-info-subtitle">Compra, alquila o comparte</div></div></section><section class="search-block"><div class="segmented">${['Comprar','Alquilar','Compartir'].map(x=>`<button class="segment ${state.operation===x?'active':''}" data-op="${x}">${x}</button>`).join('')}</div><label class="field"><select><option>Viviendas</option><option>Habitaciones</option><option>Garajes</option><option>Locales</option></select><span class="field-chevron">⌄</span></label><label class="field"><input id="location" value="${state.location}" placeholder="¿Dónde buscas?"><button class="field-icon" type="button">⌖</button></label><button class="btn primary block search-submit" data-search>Buscar</button></section><section class="home-cta"><button class="btn secondary block" data-publish>Publicar anuncio gratis</button></section><section class="section"><h2 class="section-title">Tus búsquedas</h2>${['Pisos en Madrid','Centro y Chamberí'].map((t,i)=>`<article class="search-card" data-search><img class="search-thumb" src="${i?'assets/rooms-hero.svg':'assets/property-hero.svg'}"><div><div class="search-card-title">${t}</div><div class="search-card-meta">${i?'Compra · 2 o más habitaciones':'Alquiler · hasta 2.500 €/mes'}</div></div><div class="chevron">›</div></article>`).join('')}</section></div>`}
function card(x){const on=state.favs.has(x.id);return `<article class="listing"><div class="listing-media" data-detail="${x.id}"><img src="${x.img}"><button class="fav ${on?'on':''}" data-fav="${x.id}">${on?icons.heartOn:icons.heart}</button><span class="photo-count">▣ 12</span></div><div class="listing-body" data-detail="${x.id}"><div class="listing-kicker">Destacado</div><h3 class="listing-title">${x.title}</h3><div class="listing-location">Madrid</div><div class="listing-price">${x.price}</div><div class="listing-features">${x.meta}</div><p class="listing-description">${x.desc}</p></div><div class="listing-actions"><button data-call>${icons.phone} Llamar</button><button data-message>${icons.mail} Mensaje</button></div></article>`}
function results(){return `${toolbar(state.location,{back:true})}<div class="page page-base"><div class="filter-bar"><button class="filter-action" data-filter>${icons.filter} Filtrar</button><button class="filter-action" data-sort>${icons.sort} Ordenar</button><button class="filter-action ${state.map?'active':''}" data-map>${icons.map} ${state.map?'Lista':'Mapa'}</button></div><div class="result-count">${listings.length} viviendas en ${state.location}</div>${state.map?mapView():listings.map(card).join('')}</div>`}
function mapView(){return `<section class="map"><div class="map-grid"></div><div class="map-water"></div>${listings.map((x,i)=>`<button class="pin ${i===0?'selected':''}" style="left:${24+i*25}%;top:${28+i*15}%" data-detail="${x.id}">${x.price.split('/')[0]}</button>`).join('')}<article class="map-card" data-detail="1"><img src="${listings[0].img}"><div class="map-card-body"><div class="map-card-title">${listings[0].title}</div><div class="map-card-price">${listings[0].price}</div><div class="map-card-meta">${listings[0].meta}</div></div></article></section>`}
function detail(id){const x=listings.find(v=>v.id==id)||listings[0],on=state.favs.has(x.id);return `<div class="screen no-nav"><section class="detail-hero"><img src="${x.img}"><div class="detail-top"><button class="round" data-go="results">${icons.back}</button><div class="round-actions"><button class="round">↗</button><button class="round ${on?'on':''}" data-fav="${x.id}">${on?icons.heartOn:icons.heart}</button></div></div><span class="gallery-count">1 / 12</span></section><main class="detail-content"><h1>${x.title}</h1><div class="detail-address">Madrid</div><div class="detail-price">${x.price}</div><div class="detail-features">${x.meta}</div><div class="tags"><span class="tag">Terraza</span><span class="tag">Ascensor</span><span class="tag">Aire acondicionado</span></div><section class="detail-section"><h2>Comentario del anunciante</h2><p>${x.desc} La vivienda se entrega amueblada y está disponible para entrar a vivir.</p></section><section class="detail-section"><h2>Características básicas</h2><ul><li>Buen estado</li><li>Armarios empotrados</li><li>Orientación sur</li></ul></section></main><div class="contact-fixed"><button class="btn secondary" data-call>${icons.phone} Llamar</button><button class="btn primary" data-message>${icons.mail} Mensaje</button></div></div>`}
function alerts(){return `${toolbar('',{brand:true})}<div class="page"><h2 class="section-title">Tus alertas</h2>${['Pisos en Madrid','Centro y Chamberí'].map((t,i)=>`<article class="alert-row"><img src="${i?'assets/rooms-hero.svg':'assets/property-hero.svg'}"><div><div class="row-title">${t}</div><div class="row-meta">${i?'Compra':'Alquiler'} · Activada</div></div><button class="switch on"></button></article>`).join('')}</div>`}
function favorites(){const a=listings.filter(x=>state.favs.has(x.id));return `${toolbar('',{brand:true})}<div class="page page-base">${a.length?a.map(card).join(''):`<section class="empty"><h2>Aún no tienes favoritos</h2><p>Guarda los anuncios que te gusten para encontrarlos aquí.</p><button class="btn primary" data-go="home">Buscar viviendas</button></section>`}</div>`}
function chat(){return `${toolbar('',{brand:true})}<div class="page"><h2 class="section-title">Chat</h2>${['Lucía · Particular','Inmobiliaria Centro'].map((n,i)=>`<article class="conversation"><div class="avatar">${n[0]}</div><div><div class="conv-name">${n}</div><div class="conv-preview">${i?'Te enviamos la documentación del piso.':'Sí, podemos organizar una visita mañana.'}</div></div><div><div class="conv-time">${i?'Ayer':'12:42'}</div>${i?'':'<div class="badge">2</div>'}</div></article>`).join('')}</div>`}
function menu(){return `${toolbar('',{brand:true})}<div class="page"><section class="menu-user"><div class="avatar">BG</div><div><div class="menu-user-name">Bogdan</div><div class="menu-user-email">Cuenta de demostración</div></div></section><div class="menu-heading">Tu cuenta</div>${['Perfil','Tus anuncios','Ajustes','Ayuda y contacto'].map(x=>`<button class="menu-row"><span>○</span><span class="menu-row-title">${x}</span><span class="chevron">›</span></button>`).join('')}</div>`}
function showSheet(title,body){overlay.innerHTML=`<div class="sheet-backdrop"><section class="sheet"><div class="sheet-handle"></div><div class="sheet-head"><h2>${title}</h2><button class="sheet-close" data-close>×</button></div><div class="sheet-body">${body}</div></section></div>`}
function toast(t){toastRoot.innerHTML=`<div class="toast">${t}</div>`;setTimeout(()=>toastRoot.innerHTML='',1600)}
function render(){const [base,id]=state.route.split('/');const views={home,results,alerts,favorites,chat,menu};screen.classList.toggle('no-nav',base==='detail');screen.innerHTML=base==='detail'?detail(id):(views[base]||home)();nav.classList.toggle('hidden',base==='detail');nav.innerHTML=navHtml();bind()}
function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));document.querySelectorAll('[data-op]').forEach(b=>b.onclick=()=>{state.operation=b.dataset.op;render()});document.querySelectorAll('[data-search]').forEach(b=>b.onclick=()=>{const l=$('#location');if(l)state.location=l.value||'Madrid';go('results')});document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=e=>{if(e.target.closest('[data-fav]'))return;go('detail/'+b.dataset.detail)});document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();const id=+b.dataset.fav;state.favs.has(id)?state.favs.delete(id):state.favs.add(id);save();render()});$('[data-map]')&&($('[data-map]').onclick=()=>{state.map=!state.map;render()});$('[data-filter]')&&($('[data-filter]').onclick=()=>showSheet('Filtrar',`<div class="sheet-label">Precio</div><div class="range"><input class="input" placeholder="Mínimo"><input class="input" placeholder="Máximo"></div><div class="sheet-label">Habitaciones</div><div class="choices">${['Todas','1','2','3','4+'].map(x=>`<button class="choice">${x}</button>`).join('')}</div><button class="btn primary block" style="margin-top:24px" data-close>Ver resultados</button>`));$('[data-sort]')&&($('[data-sort]').onclick=()=>showSheet('Ordenar',`<div class="sort-list"><button class="sort-option on">Relevancia</button><button class="sort-option">Precio más bajo</button><button class="sort-option">Precio más alto</button></div>`));document.querySelectorAll('[data-call]').forEach(b=>b.onclick=()=>toast('Llamando al anunciante…'));document.querySelectorAll('[data-message]').forEach(b=>b.onclick=()=>toast('Mensaje enviado'));$('[data-publish]')&&($('[data-publish]').onclick=()=>toast('Formulario de publicación abierto'));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>overlay.innerHTML='')}
window.addEventListener('hashchange',()=>{state.route=location.hash.slice(1)||'home';render()});render();
